# variable "private-subnet-1" {}
# variable "private-subnet-2" {}
# variable "private-subnet-3" {}
# variable "data_process_security_group" {}
# variable "eliptic_security_group" {}
# variable "push_notifi_security_group" {}
# variable "withdrawal_security_group" {}
# variable "pusd_noftifi_iam" {}
# variable "data_process_iam" {}
# variable "eliptic_iam" {}
# variable "push_web" {}
# variable "web_scoket_iam" {}
# variable "web_scoket_disconnect_iam" {}
# variable "withdrawal_iam" {}
# variable "isolated-subnet-1" {}
# variable "isolated-subnet-2" {}
# variable "Push_Message_web_security_group" {}
# variable "web_scoket_security_group" {}
# variable "web_scoket_disconnect_security_group" {}

